# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DijkstraSSSP <- function(Adj, Costs, source) {
    .Call('_ProjectionBasedClustering_DijkstraSSSP', PACKAGE = 'ProjectionBasedClustering', Adj, Costs, source)
}

c_NeRV <- function(data, lambda, lastNeighbor, iterations, stepsPerRound, stepsOnLastRound, randominit, outputDimension, pca) {
    .Call('_ProjectionBasedClustering_c_NeRV', PACKAGE = 'ProjectionBasedClustering', data, lambda, lastNeighbor, iterations, stepsPerRound, stepsOnLastRound, randominit, outputDimension, pca)
}

ContTrustMeasure <- function(datamat, projmat, lastNeighbor) {
    .Call('_ProjectionBasedClustering_ContTrustMeasure', PACKAGE = 'ProjectionBasedClustering', datamat, projmat, lastNeighbor)
}

KLMeasure <- function(Data, pData, NeighborhoodSize = 20L) {
    .Call('_ProjectionBasedClustering_KLMeasure', PACKAGE = 'ProjectionBasedClustering', Data, pData, NeighborhoodSize)
}

klrank <- function(Data, pData, NeighborhoodSize = 20L) {
    .Call('_ProjectionBasedClustering_klrank', PACKAGE = 'ProjectionBasedClustering', Data, pData, NeighborhoodSize)
}

opt_multicore_tnse_cpp <- function(X, no_dims, perplexity, max_iter, num_threads, theta, n_iter_early_exag, early_exaggeration, learning_rate, auto_iter, auto_iter_end, distance_squared) {
    .Call('_ProjectionBasedClustering_opt_multicore_tnse_cpp', PACKAGE = 'ProjectionBasedClustering', X, no_dims, perplexity, max_iter, num_threads, theta, n_iter_early_exag, early_exaggeration, learning_rate, auto_iter, auto_iter_end, distance_squared)
}

